### ISSUE TITLE
compilation error on release '1.6.12'

### ISSUE THREAD

**Issue by moElwan** [springbot/magento2-plugin#42]
Hello, 
we're facing error on the compilation when running `bin/magento setup:di:compile` on two different setups 
1. Production server 
PHP 7.1.22 - Magento version 2.2.2
2. local dev - fresh installation
PHP 7.1.16 - Magento version 2.2.5
![2018-09-27 18 28 27](https://user-images.githubusercontent.com/1895158/46168324-69c2ed00-c298-11e8-9c5d-b7ea4907528e.png)

the production was working with no issues, till the `1.6.12` release today
would appreciate a review from your side. and I'll investigate about this more
Thanks

**Comment by JoeyK4816** [comment]
Thanks @Mohamed-Elwan for reporting this issue.

I tested compilation with the latest version today and we received no compilation errors within version 2-1-2 through 2-2-3

`root@jkimsey:/var/www/html/magento2/2-2-3# php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 54.0 MiB
Interception cache generation... 7/7 [============================] 100% 1 min 270.0 MiB
Generated code and dependency injection configuration successfully.
`

Generally any errors magento throws are going to be permission related. Make sure /pub and /var folders have proper write permission (777). Also ensure you have run the setup:upgrade command before attempting to compile. Doing so out of order can lead to errors.

Please let us know if the issue continues after attempting these changes.

**Comment by JoeyK4816** [comment]
Hi @Mohamed-Elwan we have now released version 1.6.13. This fixed several known bugs, please let us know if you have any issues during the upgrade process after verifying the permissions and instructions from my previous comment.

**Comment by moElwan** [comment]
Hi @JoeyK4816, thanks for your interest. will test the new release today and will let you know the result. for the permissions mentioned in the previous comment it's already set and nothing changed at all I'm sure of it.

**Comment by JoeyK4816** [comment]
Closing because it has now been over 2 weeks since we had a response.
